# Generated by Django 5.2.7 on 2025-10-31 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_description', models.TextField(max_length=500)),
                ('full_description', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('elevation', models.PositiveIntegerField(blank=True, help_text='Elevation in meters', null=True)),
                ('min_days', models.PositiveIntegerField(help_text='Minimum days required')),
                ('max_days', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_cost_min', models.DecimalField(decimal_places=2, help_text='In NPR', max_digits=10)),
                ('expected_cost_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('HARD', 'Hard'), ('EXTREME', 'Extreme')], default='MODERATE', max_length=10)),
                ('best_season', models.CharField(blank=True, max_length=100)),
                ('cover_image', models.ImageField(upload_to='destinations/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('has_360_view', models.BooleanField(default=False)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinations', to='destinations.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_destinations', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='destinations', to='destinations.tag')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destination_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_360', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.destination')),
            ],
            options={
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration_days', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('ADMIN', 'Admin Created'), ('AI', 'AI Generated'), ('USER', 'User Customized')], default='ADMIN', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='destinations.destination')),
            ],
            options={
                'verbose_name_plural': 'Itineraries',
                'ordering': ['-is_default', 'duration_days'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('meals_included', models.CharField(blank=True, max_length=100)),
                ('accommodation_type', models.CharField(blank=True, max_length=100)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='destinations.itinerary')),
            ],
            options={
                'ordering': ['itinerary', 'day_number'],
                'unique_together': {('itinerary', 'day_number')},
            },
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['slug'], name='destination_slug_528bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['category', '-created_at'], name='destination_categor_577fa2_idx'),
        ),
    ]
