version: '3.8'

services:
  web:
    build: .
    container_name: heavenknows_web
    command: gunicorn --bind 0.0.0.0:4000 heavenknows.wsgi:application
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: heavenknows_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
