# Generated by Django 5.2.7 on 2025-10-31 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('duration_days', models.PositiveIntegerField()),
                ('duration_nights', models.PositiveIntegerField()),
                ('price_per_person', models.DecimalField(decimal_places=2, help_text='In NPR', max_digits=10)),
                ('group_size_min', models.PositiveIntegerField(default=1)),
                ('group_size_max', models.PositiveIntegerField()),
                ('inclusions', models.TextField(help_text="What's included in the package")),
                ('exclusions', models.TextField(help_text="What's not included")),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_to', models.DateField(blank=True, null=True)),
                ('cover_image', models.ImageField(upload_to='packages/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinations', models.ManyToManyField(related_name='packages', to='destinations.destination')),
                ('travel_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='businesses.businessprofile')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='destinations.destination')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='packages.tourpackage')),
            ],
            options={
                'verbose_name_plural': 'Package Itineraries',
                'ordering': ['package', 'day_number'],
                'unique_together': {('package', 'day_number')},
            },
        ),
    ]
