# Generated by Django 5.2.7 on 2025-10-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_business',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_local',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('TOURIST', 'Tourist'), ('TRAVEL_BUSINESS', 'Travel Business'), ('LOCAL_BUSINESS', 'Local Business'), ('MANUFACTURER', 'Local Manufacturer'), ('ADMIN', 'Admin')], default='TOURIST', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
